# Site settings
title: Aitor Iba√±ez-en txokoa
header-img: img/home-bg.jpg
email: freelance@aitoribanez.com
copyright_name: Your/Project/Corporate Name
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: "blog/"
url: "http://aitiba.github.io/"
twitter_username: aitiba
github_username:  aitiba
facebook_username:  somosaitoribanez
email_username:  freelance@aitoribanez.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
